spring:
  h2:
    console:
      enabled: true  
      path: /h2-console
      
  datasource:
    driver-class-name: org.h2.Driver 
    url: jdbc:h2:~/musinsa 
    username: sa 
    password: 
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
       format_sql: true

  main:
    web-application-type: none #웹 애플리케이션이 아님을 증명
    
#logging:
#  config: classpath:log4j2.yml
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace 