spring:
  h2:
    console:
      enabled: true  
      path: /h2-console
      
  datasource:
    driver-class-name: org.h2.Driver 
    url: jdbc:h2:~/musinsa 
    username: sa 
    password: 
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
       format_sql: true